Fitting 5 folds for each of 25 candidates, totalling 125 fits
Best Parameters: {'learning_rate': 0.5623413251903491, 'restarts': 4} 

Ratio of Train Sizes Mean Train Score [0.93793103 0.88914286 0.86920152 0.85128205 0.8428246  0.84486692
 0.84201954 0.83817664 0.8321519  0.83690205] 

Ratio of Train Sizes Mean Test Score [0.75051059 0.63021586 0.67030303 0.65850145 0.68404732 0.70595683
 0.70871316 0.66758821 0.69861768 0.71595683] 

Fitness [[1.28081916e+00 6.82600000e+03]
 [1.27481554e+00 6.82800000e+03]
 [1.16227550e+00 6.83000000e+03]
 ...
 [4.01992634e-01 8.53500000e+03]
 [4.01992634e-01 8.53600000e+03]
 [4.01992634e-01 8.53700000e+03]]
Time to Train: 5.152772903442383 

Test Accuracy: 0.7105263157894737 

Final Train Accuracy: 0.8269581056466302 

f1: 0.5953177257525083 
 accuracy: 0.7105263157894737 precision: 0.6054421768707483 
 recall: 0.5855263157894737
Confusion Matrix: [[208  58]
 [ 63  89]] 

Time to Test: 0.1080780029296875 

Exception ignored in atexit callback: <bound method Gcf.destroy_all of <class 'matplotlib._pylab_helpers.Gcf'>>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/7641/lib/python3.10/site-packages/matplotlib/_pylab_helpers.py", line 90, in destroy_all
    manager.destroy()
  File "/opt/miniconda3/envs/7641/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 513, in destroy
    delayed_destroy()
  File "/opt/miniconda3/envs/7641/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 503, in delayed_destroy
    self.window.destroy()
  File "/opt/miniconda3/envs/7641/lib/python3.10/tkinter/__init__.py", line 2341, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
(7641) maimoon@Maimoons-MacBook-Air Project 2 % 